//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fondo9Sa3ada.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int review_ID { get; set; }
        public Nullable<int> reservation_ID { get; set; }
        public Nullable<int> roomId { get; set; }
        public string review1 { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
